INSERT INTO Essays (title, resources, own_resources, content_of_presentation, content_of_examples, resume_of_presentation, keywords, comments, user_id)
VALUES
    ('Artificial Intelligence in Healthcare', 
     'Medical journals, AI whitepapers', 
     'Personal research and interviews', 
     'AI applications in diagnostics and treatment', 
     'Case studies of AI in hospitals', 
     'Summary of key AI benefits and challenges', 
     'AI, Healthcare, Technology', 
     'Well-structured but needs more case studies', 
     7),

    ('Renewable Energy Sources', 
     'Energy reports, industry papers', 
     'Experiments with solar panels', 
     'Types of renewable energy and their efficiency', 
     'Solar and wind energy implementation', 
     'Comparison of energy sources', 
     'Renewable, Solar, Wind, Efficiency', 
     'Needs data validation', 
     7),

    ('Blockchain Technology', 
     'Tech blogs, blockchain whitepapers', 
     'Created a demo blockchain', 
     'Decentralization and security aspects', 
     'Real-world blockchain applications', 
     'Potential of blockchain in various sectors', 
     'Blockchain, Security, Decentralization', 
     'Great structure but lacks practical examples', 
     7),

    ('Cybersecurity Trends', 
     'Cybersecurity conferences, reports', 
     'Network security project experience', 
     'Threats and mitigation strategies', 
     'Cyberattacks case studies', 
     'Summary of latest cybersecurity trends', 
     'Cybersecurity, Threats, Protection', 
     'Well-researched but too technical', 
     7),

    ('The Future of Space Exploration', 
     'NASA reports, space missions', 
     'Self-research on Mars missions', 
     'Mars exploration plans and technologies', 
     'Examples of past space missions', 
     'Challenges and opportunities in space travel', 
     'Space, Exploration, Mars', 
     'Great insights, consider adding cost analysis', 
     7),

    ('Social Media and Mental Health', 
     'Psychology papers, social media trends', 
     'Survey results from students', 
     'Impact of social media on mental health', 
     'Real-life case studies', 
     'Summary of mental health findings', 
     'Social Media, Mental Health, Psychology', 
     'Needs more statistical backing', 
     7),

    ('Quantum Computing Overview', 
     'Quantum mechanics textbooks, online courses', 
     'Personal simulations', 
     'Basics and applications of quantum computing', 
     'Examples of quantum algorithms', 
     'Comparison with classical computing', 
     'Quantum, Computing, Algorithms', 
     'Well-detailed but needs practical examples', 
     7),

    ('Big Data Analytics', 
     'Big data textbooks, online reports', 
     'Self-implemented analytics on datasets', 
     'Challenges and techniques in big data', 
     'Examples of big data use cases', 
     'Summary of big data advantages', 
     'Big Data, Analytics, Trends', 
     'Good work, consider adding visualization', 
     7),

    ('Ethics in Artificial Intelligence', 
     'Ethics papers, AI discussions', 
     'Survey among AI professionals', 
     'Ethical considerations in AI', 
     'Examples of ethical dilemmas', 
     'AI ethics and moral challenges', 
     'AI, Ethics, Morality', 
     'Interesting but needs more real-world examples', 
     7),

    ('Impact of Climate Change', 
     'Climate change reports, research papers', 
     'Local environmental observations', 
     'Effects of climate change on ecosystems', 
     'Examples of climate change impact globally', 
     'Solutions to combat climate change', 
     'Climate, Environment, Global Warming', 
     'Great insights but needs actionable steps', 
     7);

INSERT INTO Projects (title, description, example_distribution_1, example_distribution_2, example_distribution_3, integration, requirements, comments)
VALUES
    ('Smart Home Automation System', 
     'A system to automate home appliances using IoT devices.', 
     'Temperature control using smart thermostats.', 
     'Smart lighting automation.', 
     'Voice-controlled home assistant.', 
     'Integration with mobile app and cloud storage.', 
     'Wi-Fi connectivity, smart devices, cloud API.', 
     'Consider adding more security features.'),

    ('E-Commerce Website', 
     'An online platform for buying and selling products.', 
     'User authentication and profile management.', 
     'Product catalog and search functionality.', 
     'Shopping cart and payment gateway.', 
     'Integration with logistics services.', 
     'Secure database, responsive design, SEO optimization.', 
     'Improve checkout process for better UX.'),

    ('AI-Powered Chatbot', 
     'A chatbot for customer service automation.', 
     'Natural language processing for user queries.', 
     'Sentiment analysis for better responses.', 
     'Automated ticket generation.', 
     'Integration with CRM systems.', 
     'Machine learning models, cloud deployment.', 
     'Make responses more human-like.'),

    ('Health Monitoring System', 
     'A wearable health monitoring system for tracking vitals.', 
     'Heart rate and blood pressure monitoring.', 
     'Step counting and calorie tracking.', 
     'Sleep pattern analysis.', 
     'Integration with mobile health apps.', 
     'Wearable sensors, Bluetooth connectivity.', 
     'Ensure data accuracy in readings.'),

    ('Online Learning Platform', 
     'A web-based platform for remote learning.', 
     'Course creation and management.', 
     'Student progress tracking.', 
     'Live class streaming.', 
     'Integration with third-party tools like Zoom.', 
     'Scalable cloud infrastructure, responsive design.', 
     'Consider adding gamification elements.'),

    ('Autonomous Delivery Drone', 
     'A drone system for autonomous package delivery.', 
     'Automated route planning.', 
     'Real-time obstacle detection.', 
     'Parcel handling mechanism.', 
     'Integration with delivery management systems.', 
     'GPS tracking, battery optimization.', 
     'Test in diverse weather conditions.'),

    ('Cybersecurity Threat Detection', 
     'A system to detect and mitigate cyber threats.', 
     'Anomaly detection in network traffic.', 
     'User behavior analytics.', 
     'Automated response to detected threats.', 
     'Integration with firewall systems.', 
     'Machine learning, real-time monitoring.', 
     'Ensure compliance with security standards.'),

    ('Inventory Management System', 
     'A software for tracking inventory in warehouses.', 
     'Barcode scanning for product tracking.', 
     'Automated stock level alerts.', 
     'Supplier management and reporting.', 
     'Integration with accounting software.', 
     'Cloud-based storage, real-time updates.', 
     'Optimize search functionality for large inventories.'),

    ('Virtual Reality Fitness App', 
     'An immersive VR-based fitness training application.', 
     'Virtual personal trainer experience.', 
     'Customizable workout plans.', 
     'Real-time performance tracking.', 
     'Integration with fitness wearables.', 
     'VR headset compatibility, cloud storage.', 
     'Enhance motion tracking accuracy.'),

    ('Smart Traffic Management System', 
     'A system to optimize traffic flow using IoT sensors.', 
     'Real-time traffic congestion monitoring.', 
     'Automatic signal timing adjustment.', 
     'Emergency vehicle prioritization.', 
     'Integration with city-wide surveillance.', 
     'IoT sensors, data analytics.', 
     'Improve system response time during peak hours.');

